apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-management
  name: user-management
spec:
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31911
  selector:
    app: user-management
  type: NodePort
status:
  loadBalancer: {}
