
version: '3.9'

services:
  user-management:
    build: .
    container_name: user-management
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_PATH=database/db.sqlite



