apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-management-testing
  name: user-management-testing
spec:
  ports:
    - name: "3001"
      port: 3001
      protocol: TCP
      targetPort: 3001
      nodePort: 31912
  selector:
    app: user-management-testing
  type: NodePort
status:
  loadBalancer: {}
